### ISSUE TITLE
Readme broken - require.js not defined

### ISSUE THREAD

**Issue by katieburke60** [learn-co-curriculum/plotting-data-readme#3]
@JeffKatzy @tkoar The engineering team noticed an [error](https://flatironlabs.airbrake.io/projects/104717/groups/2261117055389457944?filters=%7B%22order%22:%22last_notice%22,%22resolved%22:%22false%22,%22search%22:%22qa%22%7D&tab=overview) in the README on line 44 the require.js is not defined. 

Looks like it has been broken since the readme was created.

**Comment by tkoar** [comment]
closed with commit 2edb622
